sudo: required
dist: xenial
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script: pytest
after_script: cd ~
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: ${{ secrets.PYPI_API_TOKEN }}
  on:
    repo: daniel-furman/lwMCMC
    branches:    
      only:    
        - master 
