sudo: required
dist: xenial
language: python
virtualenv:
  system_site_packages: true
python:
- '3.6'
install:
- pip install -r requirements.txt
script: pytest
after_script: cd ~
- name: Publish distribution 📦 to Test PyPI
  uses: pypa/gh-action-pypi-publish@master
  with:
    password: ${{ secrets.TEST_PYPI_API_TOKEN }}
    repository_url: https://test.pypi.org/legacy/
- name: Publish distribution 📦 to PyPI
  if: startsWith(github.ref, 'refs/tags')
  uses: pypa/gh-action-pypi-publish@master
  with:
     password: ${{ secrets.PYPI_API_TOKEN }}
